// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igdirwxwtlqvodmtknwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZGlyd3h3dGxxdm9kbXRrbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDg0NzEsImV4cCI6MjA2MTQyNDQ3MX0.t9mDqRY0JRMDXQUeRrF76hCT0qwNQ-hkCa7_gUpdZQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);